# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-29 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='project_type',
            field=models.CharField(choices=[(b'GameFi', b'GameFi'), (b'PublicChain', b'PublicChain')], default=b'GameFi', max_length=10),
        ),
        migrations.AlterField(
            model_name='token',
            name='name',
            field=models.CharField(default=b'Project Name', max_length=50, verbose_name=b'Name'),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default=b'Token', max_length=50, verbose_name=b'Token'),
        ),
    ]
