# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-29 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ido', '0002_auto_20210829_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='vest',
            field=models.CharField(blank=True, default=b'', max_length=1000, verbose_name=b'Vest'),
        ),
    ]
