# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-29 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ido', '0003_token_vest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='vest',
            new_name='vesting',
        ),
        migrations.AlterField(
            model_name='token',
            name='project_type',
            field=models.CharField(blank=True, default=b'', max_length=50, verbose_name=b'Project Type'),
        ),
        migrations.AlterField(
            model_name='token',
            name='token_type',
            field=models.CharField(choices=[(b'BTC', b'BTC'), (b'ETH', b'ETH'), (b'BNB', b'BNB'), (b'BNB', b'BNB')], default=b'ETH', max_length=10),
        ),
    ]
