# Generated by Django 3.2.7 on 2021-09-02 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ido', '0007_auto_20210829_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='current_price',
            field=models.FloatField(default=0, verbose_name='Current Price'),
        ),
        migrations.AlterField(
            model_name='token',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='token',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='token',
            name='name',
            field=models.CharField(default='Project Name', max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='token',
            name='platform',
            field=models.CharField(choices=[('CoinList', 'CoinList'), ('Miso', 'Miso'), ('DaoMaker', 'DaoMaker'), ('LaunchZone', 'LaunchZone'), ('FTX', 'FTX')], default='CoinList', max_length=10),
        ),
        migrations.AlterField(
            model_name='token',
            name='price',
            field=models.FloatField(default=0, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='token',
            name='project_type',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Project Type'),
        ),
        migrations.AlterField(
            model_name='token',
            name='quantity',
            field=models.FloatField(default=0, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default='Token', max_length=50, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='token',
            name='token_type',
            field=models.CharField(choices=[('ETH', 'ETH'), ('BNB', 'BNB'), ('USDT', 'USDT')], default='ETH', max_length=10),
        ),
        migrations.AlterField(
            model_name='token',
            name='token_used',
            field=models.FloatField(default=0, verbose_name='Token Used'),
        ),
        migrations.AlterField(
            model_name='token',
            name='vesting',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Vest'),
        ),
    ]
