# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-02 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'Game', max_length=50, verbose_name=b'Name')),
                ('url', models.CharField(default=b'', max_length=250, verbose_name=b'Url')),
                ('token', models.CharField(default=b'', max_length=100, verbose_name=b'Token')),
                ('description', models.CharField(blank=True, default=b'', max_length=1000, verbose_name=b'Description')),
            ],
        ),
    ]
