# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-02 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamefi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(default=b'Game', max_length=50, verbose_name=b'Name')),
                ('address', models.CharField(default=b'', max_length=100, verbose_name=b'Address')),
                ('chain_token_balance', models.FloatField(default=0, verbose_name=b'Chain Token')),
                ('game_token_balance', models.FloatField(default=0, verbose_name=b'Game Token')),
                ('description', models.CharField(blank=True, default=b'', max_length=1000, verbose_name=b'Description')),
            ],
        ),
    ]
