# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-02 07:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamefi', '0003_auto_20210802_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='game',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='gamefi.Game', verbose_name=b'Game'),
        ),
    ]
