# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-02 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamefi', '0005_game_chain'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='invest',
            field=models.FloatField(default=0, verbose_name=b'Investment'),
        ),
    ]
