# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-03 02:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamefi', '0010_auto_20210803_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSettlement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_game_token_balance', models.FloatField(default=0, verbose_name=b'Game Token Balance(Last)')),
                ('game_token_income', models.FloatField(default=0, verbose_name=b'Income')),
                ('game_token_payout', models.FloatField(default=0, verbose_name=b'Payout')),
                ('game_token_balance', models.FloatField(default=0, verbose_name=b'Game Token Balance')),
                ('settle_time', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name=b'SettleTime')),
                ('game', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements', to='gamefi.Game', verbose_name=b'Game')),
            ],
        ),
    ]
