# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-03 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamefi', '0011_gamesettlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='game_token_balance_not_claimed',
            field=models.FloatField(default=0, verbose_name=b'Game Token Not Claimed'),
        ),
    ]
