# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-12 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamefi', '0014_game_chain_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='output_game_token',
            field=models.FloatField(default=0, verbose_name=b'Output Game Token'),
        ),
    ]
