# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-30 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamefi', '0015_game_output_game_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='stage',
            field=models.CharField(choices=[(b'Pre', b'Pre'), (b'Gaming', b'Gaming'), (b'Suspend', b'Suspend'), (b'Terminated', b'Terminated')], default=b'Pre', max_length=10),
        ),
    ]
