# Generated by Django 3.2.7 on 2021-09-02 11:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamefi', '0016_game_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=models.CharField(default='0', max_length=50, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.CharField(default='', max_length=100, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='account',
            name='chain_token_balance',
            field=models.FloatField(default=0, verbose_name='Chain Token'),
        ),
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='account',
            name='game',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='gamefi.game', verbose_name='Game'),
        ),
        migrations.AlterField(
            model_name='account',
            name='game_token_balance',
            field=models.FloatField(default=0, verbose_name='Game Token'),
        ),
        migrations.AlterField(
            model_name='account',
            name='game_token_balance_not_claimed',
            field=models.FloatField(default=0, verbose_name='Game Token Not Claimed'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Main Account'),
        ),
        migrations.AlterField(
            model_name='game',
            name='chain',
            field=models.CharField(choices=[('BSC', 'BSC'), ('ETH', 'ETH')], default='BSC', max_length=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='chain_price',
            field=models.FloatField(default=0, verbose_name='Chain Price'),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='game',
            name='input',
            field=models.FloatField(default=0, verbose_name='Input'),
        ),
        migrations.AlterField(
            model_name='game',
            name='last_game_token_balance',
            field=models.FloatField(default=0, verbose_name='Game Token Balance(Last)'),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(default='Game', max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='game',
            name='output_game_token',
            field=models.FloatField(default=0, verbose_name='Output Game Token'),
        ),
        migrations.AlterField(
            model_name='game',
            name='stage',
            field=models.CharField(choices=[('Pre', 'Pre'), ('Gaming', 'Gaming'), ('Suspend', 'Suspend'), ('Terminated', 'Terminated')], default='Pre', max_length=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='token',
            field=models.CharField(default='', max_length=100, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='game',
            name='token_price',
            field=models.FloatField(default=0, verbose_name='Token Price'),
        ),
        migrations.AlterField(
            model_name='game',
            name='url',
            field=models.CharField(default='', max_length=250, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='gamesettlement',
            name='game',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements', to='gamefi.game', verbose_name='Game'),
        ),
        migrations.AlterField(
            model_name='gamesettlement',
            name='game_token_balance',
            field=models.FloatField(default=0, verbose_name='Game Token Balance'),
        ),
        migrations.AlterField(
            model_name='gamesettlement',
            name='game_token_income',
            field=models.FloatField(default=0, verbose_name='Income'),
        ),
        migrations.AlterField(
            model_name='gamesettlement',
            name='game_token_payout',
            field=models.FloatField(default=0, verbose_name='Payout'),
        ),
        migrations.AlterField(
            model_name='gamesettlement',
            name='last_game_token_balance',
            field=models.FloatField(default=0, verbose_name='Game Token Balance(Last)'),
        ),
        migrations.AlterField(
            model_name='gamesettlement',
            name='settle_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='SettleTime'),
        ),
    ]
