# Generated by Django 3.2.7 on 2021-09-03 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamefi', '0017_auto_20210902_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(default='0', max_length=50, verbose_name='ID')),
                ('game_token_balance', models.FloatField(default=0, verbose_name='Game Token')),
                ('game_token_balance_not_claimed', models.FloatField(default=0, verbose_name='Game Token Not Claimed')),
                ('description', models.CharField(blank=True, default='', max_length=1000, verbose_name='Description')),
                ('address', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_accounts', to='gamefi.account', verbose_name='Address')),
                ('game', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_accounts', to='gamefi.game', verbose_name='Game')),
            ],
            options={
                'ordering': ['account_id'],
            },
        ),
    ]
