# Generated by Django 3.2.7 on 2021-09-03 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamefi', '0018_gameaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='token',
        ),
    ]
