# Generated by Django 3.2.7 on 2021-09-03 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0006_token_precision'),
        ('gamefi', '0019_remove_game_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='token',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='basic.token', verbose_name='Token'),
        ),
    ]
