# Generated by Django 3.2.7 on 2021-09-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Token', max_length=50, verbose_name='Name')),
                ('symbol', models.CharField(default='Symbol', max_length=50, verbose_name='Symbol')),
                ('price_source', models.CharField(choices=[('CoinGecko', 'CoinGecko')], default='CoinGecko', max_length=10)),
                ('price_symbol', models.CharField(default='Symbol', max_length=50, verbose_name='Price Symbol')),
                ('current_price', models.FloatField(default=0, verbose_name='Current Price')),
                ('description', models.CharField(blank=True, default='', max_length=1000, verbose_name='Description')),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
    ]
