# Generated by Django 3.2.7 on 2021-09-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='chain_type',
            field=models.CharField(choices=[('MAIN', 'MAIN'), ('ETH', 'ETH'), ('BNB', 'BNB')], default='MAIN', max_length=10),
        ),
    ]
