# Generated by Django 3.2.7 on 2021-09-03 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_alter_token_contract_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='contract_address',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Contract Address'),
        ),
    ]
