# Generated by Django 3.2.7 on 2021-09-03 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0005_alter_token_contract_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='precision',
            field=models.IntegerField(default=18, verbose_name='Precision'),
        ),
    ]
