# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-14 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlotConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'Config Name', max_length=50, verbose_name=b'Name')),
                ('k', models.CharField(default=b'32', max_length=10, verbose_name=b'K Size')),
                ('e', models.BooleanField(default=False, verbose_name=b'Bitfield')),
                ('n_threads', models.IntegerField(default=3, verbose_name=b'Threads')),
                ('n_buckets', models.IntegerField(default=128, verbose_name=b'Buckets')),
                ('job_buffer', models.IntegerField(default=4200, verbose_name=b'Job Buffer')),
                ('global_max_jobs', models.IntegerField(default=12, verbose_name=b'Global Max Jobs')),
                ('global_stagger_m', models.IntegerField(default=24, verbose_name=b'Global Stagger Time')),
                ('tmpdir_max_jobs', models.IntegerField(default=12, verbose_name=b'Tmp Max Jobs')),
                ('tmpdir_stagger_phase_major', models.IntegerField(default=2, verbose_name=b'Tmp Stagger Phase Major')),
                ('tmpdir_stagger_phase_minor', models.IntegerField(default=1, verbose_name=b'Tmp Stagger Phase Minor')),
                ('tmpdir_stagger_phase_limit', models.IntegerField(default=5, verbose_name=b'Tmp Stagger Phase Limit')),
                ('description', models.CharField(blank=True, default=b'', max_length=1000, verbose_name=b'Description')),
            ],
        ),
    ]
