# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-14 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_plotconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotconfig',
            name='e',
            field=models.BooleanField(default=True, verbose_name=b'Bitfield'),
        ),
    ]
