# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-14 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20210514_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotter',
            name='plot_config',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='server.PlotConfig', verbose_name=b'PlotConfig'),
        ),
        migrations.AddField(
            model_name='plotter',
            name='plot_config_applied',
            field=models.BooleanField(default=False, verbose_name=b'Plot Config Applied'),
        ),
    ]
