# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-14 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20210514_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotter',
            name='server_number',
            field=models.CharField(default=b'001', max_length=50, verbose_name=b'Server Id'),
        ),
    ]
