# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-15 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20210514_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotter',
            name='cache_type',
            field=models.CharField(choices=[(b'3.2*1', b'3.2*1'), (b'3.2*2', b'3.2*2'), (b'4.0*1', b'4.0*1'), (b'4.0*2', b'4.0*2'), (b'6.4*1', b'6.4*1')], default=b'3.2*1', max_length=20, verbose_name=b'Cache Type'),
        ),
    ]
