# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-16 08:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_plotconfig_cache_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Harvester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_number', models.CharField(default=b'001', max_length=50, verbose_name=b'Server Id')),
                ('internal_ip', models.CharField(blank=True, default=b'', max_length=20, verbose_name=b'Internal IP')),
                ('plots_cnt', models.IntegerField(default=0, verbose_name=b'Plot Count')),
                ('driver_cnt', models.IntegerField(default=0, verbose_name=b'Driver Count')),
                ('description', models.CharField(blank=True, default=b'', max_length=1000, verbose_name=b'Description')),
                ('last_heartbeat_time', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name=b'Heartbeat')),
            ],
        ),
        migrations.AlterField(
            model_name='plotconfig',
            name='global_max_jobs',
            field=models.IntegerField(default=12, verbose_name=b'Max Jobs'),
        ),
        migrations.AlterField(
            model_name='plotconfig',
            name='global_stagger_m',
            field=models.IntegerField(default=24, verbose_name=b'Stagger'),
        ),
        migrations.AlterField(
            model_name='plotconfig',
            name='tmpdir_max_jobs',
            field=models.IntegerField(default=12, verbose_name=b'Max Jobs(Tmp)'),
        ),
        migrations.AlterField(
            model_name='plotconfig',
            name='tmpdir_stagger_phase_limit',
            field=models.IntegerField(default=5, verbose_name=b'Phase Limit'),
        ),
        migrations.AlterField(
            model_name='plotconfig',
            name='tmpdir_stagger_phase_major',
            field=models.IntegerField(default=2, verbose_name=b'Phase Major'),
        ),
        migrations.AlterField(
            model_name='plotconfig',
            name='tmpdir_stagger_phase_minor',
            field=models.IntegerField(default=1, verbose_name=b'Phase Minor'),
        ),
        migrations.AlterField(
            model_name='plotter',
            name='st_plot_output',
            field=models.IntegerField(default=0, verbose_name=b'Output'),
        ),
    ]
