# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-16 09:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_auto_20210516_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='harvester',
            old_name='plots_cnt',
            new_name='plot_cnt',
        ),
    ]
