# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-16 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_auto_20210516_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotter',
            name='internal_ip',
            field=models.CharField(blank=True, default=b'', max_length=20, verbose_name=b'Internal IP'),
        ),
        migrations.AddField(
            model_name='plotter',
            name='is_sending_run',
            field=models.BooleanField(default=False, verbose_name=b'Sending Process'),
        ),
    ]
