# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-16 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0014_plottransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='plottransfer',
            name='plot_file_name',
            field=models.CharField(default=b'default name', max_length=254, verbose_name=b'Plot File'),
        ),
    ]
