# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-16 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0015_plottransfer_plot_file_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plottransfer',
            old_name='internal_ip',
            new_name='harvester_ip',
        ),
    ]
