# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-17 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0016_auto_20210516_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotter',
            name='is_plotting_run',
            field=models.BooleanField(default=False, verbose_name=b'Is Plotting run'),
        ),
    ]
