# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-17 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0017_plotter_is_plotting_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='plottransfer',
            name='harvester_path',
            field=models.CharField(blank=True, default=b'', max_length=254, verbose_name=b'Path'),
        ),
        migrations.AddField(
            model_name='plottransfer',
            name='nc_pid',
            field=models.CharField(blank=True, default=b'', max_length=10, verbose_name=b'NC pid'),
        ),
        migrations.AddField(
            model_name='plottransfer',
            name='nc_port',
            field=models.CharField(blank=True, default=b'', max_length=10, verbose_name=b'NC port'),
        ),
        migrations.AddField(
            model_name='plottransfer',
            name='plotter_path',
            field=models.CharField(blank=True, default=b'', max_length=254, verbose_name=b'Path'),
        ),
    ]
