# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-19 05:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0018_auto_20210517_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotter',
            name='boot_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name=b'Boot Time'),
        ),
        migrations.AlterField(
            model_name='plotconfig',
            name='cache_type',
            field=models.CharField(choices=[(b'3.2*1', b'3.2*1'), (b'3.2*2', b'3.2*2'), (b'4.0*1', b'4.0*1'), (b'4.0*2', b'4.0*2'), (b'6.4*1', b'6.4*1'), (b'6.4*2', b'6.4*2'), (b'4.0*4', b'4.0*4'), (b'2.0(m2)m*4', b'2.0(m2)m*4')], default=b'3.2*1', max_length=20, verbose_name=b'Cache Type'),
        ),
        migrations.AlterField(
            model_name='plotter',
            name='cache_type',
            field=models.CharField(choices=[(b'3.2*1', b'3.2*1'), (b'3.2*2', b'3.2*2'), (b'4.0*1', b'4.0*1'), (b'4.0*2', b'4.0*2'), (b'6.4*1', b'6.4*1'), (b'6.4*2', b'6.4*2'), (b'4.0*4', b'4.0*4'), (b'2.0(m2)m*4', b'2.0(m2)m*4')], default=b'3.2*1', max_length=20, verbose_name=b'Cache Type'),
        ),
        migrations.AlterField(
            model_name='plotter',
            name='is_plotting_run',
            field=models.BooleanField(default=False, verbose_name=b'Plotting'),
        ),
        migrations.AlterField(
            model_name='plotter',
            name='is_sending_run',
            field=models.BooleanField(default=False, verbose_name=b'Sending'),
        ),
    ]
