# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-19 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0019_auto_20210519_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotconfig',
            name='job_buffer',
            field=models.IntegerField(default=4000, verbose_name=b'Job Buffer'),
        ),
    ]
