# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-22 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0020_auto_20210519_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotter',
            name='cpu_cnt',
            field=models.IntegerField(default=0, verbose_name=b'CPU Count'),
        ),
        migrations.AddField(
            model_name='plotter',
            name='cpu_model',
            field=models.CharField(blank=True, default=b'', max_length=100, verbose_name=b'CPU'),
        ),
        migrations.AddField(
            model_name='plotter',
            name='memory_total',
            field=models.IntegerField(default=0, verbose_name=b'Memory Total'),
        ),
        migrations.AddField(
            model_name='plotter',
            name='memory_used',
            field=models.IntegerField(default=0, verbose_name=b'Memory Used'),
        ),
    ]
