# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-22 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0022_auto_20210522_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotter',
            name='cpu_used_percnet',
            field=models.FloatField(default=0, verbose_name=b'CPU Used Percnet'),
        ),
    ]
