# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-22 03:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0023_plotter_cpu_used_percnet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plotter',
            old_name='cpu_used_percnet',
            new_name='cpu_used_percent',
        ),
    ]
