# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-22 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0024_auto_20210522_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotter',
            name='cache_cnt',
            field=models.IntegerField(default=1, verbose_name=b'SSD Count'),
        ),
    ]
