# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-23 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0025_plotter_cache_cnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotter',
            name='is_cache_raid0',
            field=models.BooleanField(default=False, verbose_name=b'Cache Raid0'),
        ),
    ]
