# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-23 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0026_plotter_is_cache_raid0'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotter',
            name='exclude_dst_paths',
            field=models.CharField(blank=True, default=b'', max_length=1000, verbose_name=b'Exclude Dst Paths'),
        ),
    ]
