# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-26 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0028_auto_20210523_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotter',
            name='uptime',
            field=models.IntegerField(blank=True, default=0, verbose_name=b'Uptime'),
        ),
    ]
