# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-27 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0029_plotter_uptime'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotter',
            name='nvme_cnt',
            field=models.IntegerField(default=1, verbose_name=b'NVME Count'),
        ),
        migrations.AddField(
            model_name='plotter',
            name='nvme_size',
            field=models.FloatField(default=0, verbose_name=b'NVME Size'),
        ),
        migrations.AlterField(
            model_name='plotter',
            name='cpu_used_percent',
            field=models.FloatField(default=0, verbose_name=b'CPU Used Percent'),
        ),
    ]
