# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-28 13:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0030_auto_20210527_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotter',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name=b'HeartBeat'),
        ),
    ]
