# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-28 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0031_plotter_last_heartbeat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotter',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name=b'HeartBeat'),
        ),
    ]
