# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-28 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0032_auto_20210528_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plotter',
            name='is_cache_raid0',
        ),
        migrations.AddField(
            model_name='plotter',
            name='is_cache_raid',
            field=models.BooleanField(default=False, verbose_name=b'Cache Raid'),
        ),
        migrations.AlterField(
            model_name='plotter',
            name='server_number',
            field=models.CharField(default=b'001', max_length=50, verbose_name=b'Id'),
        ),
    ]
