# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-28 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0035_auto_20210528_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plotter',
            name='cache_cnt',
        ),
        migrations.RemoveField(
            model_name='plotter',
            name='cache_type',
        ),
    ]
