# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-30 01:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0036_auto_20210528_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvester',
            name='boot_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name=b'Boot Time'),
        ),
        migrations.AddField(
            model_name='harvester',
            name='cpu_cnt',
            field=models.IntegerField(default=0, verbose_name=b'CPU Count'),
        ),
        migrations.AddField(
            model_name='harvester',
            name='cpu_model',
            field=models.CharField(blank=True, default=b'', max_length=100, verbose_name=b'CPU'),
        ),
        migrations.AddField(
            model_name='harvester',
            name='cpu_used_percent',
            field=models.FloatField(default=0, verbose_name=b'CPU Used Percent'),
        ),
        migrations.AddField(
            model_name='harvester',
            name='memory_total',
            field=models.BigIntegerField(default=0, verbose_name=b'Memory Total'),
        ),
        migrations.AddField(
            model_name='harvester',
            name='memory_used',
            field=models.BigIntegerField(default=0, verbose_name=b'Memory Used'),
        ),
        migrations.AddField(
            model_name='harvester',
            name='uptime',
            field=models.IntegerField(blank=True, default=0, verbose_name=b'Uptime'),
        ),
    ]
