# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-14 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0039_auto_20210530_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvester',
            name='data_tx_ip',
            field=models.CharField(blank=True, default=b'', max_length=20, verbose_name=b'Data Transfer IP'),
        ),
    ]
