# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-16 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0041_plotter_plot_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotter',
            name='plot_cnt',
            field=models.IntegerField(default=0, verbose_name=b'Plot Count'),
        ),
    ]
