# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-16 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0042_plotter_plot_cnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotter',
            name='data_interface',
            field=models.CharField(blank=True, default=b'', max_length=100, verbose_name=b'Data Network Card'),
        ),
    ]
