# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-16 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0043_plotter_data_interface'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotter',
            name='plot_file_path_expand',
            field=models.CharField(blank=True, default=b'', max_length=1000, verbose_name=b'Plot File Path(Expand)'),
        ),
    ]
