# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-18 03:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0045_harvester_auto_scan_plot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='harvester',
            old_name='plot_cnt',
            new_name='total_current_plots',
        ),
    ]
