# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-19 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0047_harvester_space_free_plots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotter',
            name='plot_config',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plotters', to='server.PlotConfig', verbose_name=b'PlotConfig'),
        ),
    ]
