# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-19 11:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0049_auto_20210619_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='harvester',
            old_name='data_tx_ip',
            new_name='data_ip',
        ),
    ]
