# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-19 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0050_auto_20210619_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harvester',
            name='internal_ip',
        ),
        migrations.AddField(
            model_name='harvester',
            name='biz_ip',
            field=models.CharField(blank=True, default=b'', max_length=20, verbose_name=b'Biz IP'),
        ),
        migrations.AlterField(
            model_name='harvester',
            name='data_ip',
            field=models.CharField(blank=True, default=b'', max_length=20, verbose_name=b'Data IP'),
        ),
    ]
