# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-19 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0051_auto_20210619_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvester',
            name='biz_interface',
            field=models.CharField(blank=True, default=b'', max_length=100, verbose_name=b'Biz Interface'),
        ),
        migrations.AddField(
            model_name='harvester',
            name='data_interface',
            field=models.CharField(blank=True, default=b'', max_length=100, verbose_name=b'Data Interface'),
        ),
    ]
