# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-19 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0052_auto_20210619_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvester',
            name='nc_process_cnt',
            field=models.IntegerField(default=0, verbose_name=b'NC Process CNT'),
        ),
    ]
