# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-21 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0053_harvester_nc_process_cnt'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlotKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'Config Name', max_length=50, verbose_name=b'Name')),
                ('farmer_pk', models.CharField(default=b'', max_length=250, verbose_name=b'Farmer Key')),
                ('pool_key', models.CharField(default=b'', max_length=250, verbose_name=b'Pool Key')),
                ('description', models.CharField(blank=True, default=b'', max_length=1000, verbose_name=b'Description')),
            ],
        ),
        migrations.AlterModelOptions(
            name='harvester',
            options={'ordering': ['server_number']},
        ),
    ]
