# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-24 01:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0055_harvesterservice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='harvesterservice',
            old_name='name',
            new_name='service',
        ),
    ]
