# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-28 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0057_auto_20210624_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotter',
            name='is_monero_run',
            field=models.BooleanField(default=False, verbose_name=b'Monero'),
        ),
    ]
