# Generated by Django 3.2.7 on 2021-09-02 11:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0058_plotter_is_monero_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvester',
            name='auto_scan_plot',
            field=models.BooleanField(default=False, verbose_name='Auto Scan'),
        ),
        migrations.AlterField(
            model_name='harvester',
            name='biz_interface',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Biz Interface'),
        ),
        migrations.AlterField(
            model_name='harvester',
            name='biz_ip',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Biz IP'),
        ),
        migrations.AlterField(
            model_name='harvester',
            name='boot_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Boot Time'),
        ),
        migrations.AlterField(
            model_name='harvester',
            name='cpu_cnt',
            field=models.IntegerField(default=0, verbose_name='CPU Count'),
        ),
        migrations.AlterField(
            model_name='harvester',
            name='cpu_model',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='CPU'),
        ),
        migrations.AlterField(
            model_name='harvester',
            name='cpu_used_percent',
            field=models.FloatField(default=0, verbose_name='CPU Used Percent'),
        ),
        migrations.AlterField(
            model_name='harvester',
            name='data_interface',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Data Interface'),
        ),
        migrations.AlterField(
            model_name='harvester',
            name='data_ip',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Data IP'),
        ),
        migrations.AlterField(
            model_name='harvester',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='harvester',
            name='driver_cnt',
            field=models.IntegerField(default=0, verbose_name='Drivers'),
        ),
        migrations.AlterField(
            model_name='harvester',
            name='file_cnt',
            field=models.IntegerField(default=0, verbose_name='Files'),
        ),
        migrations.AlterField(
            model_name='harvester',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Heartbeat'),
        ),
        migrations.AlterField(
            model_name='harvester',
            name='memory_total',
            field=models.BigIntegerField(default=0, verbose_name='Memory Total'),
        ),
        migrations.AlterField(
            model_name='harvester',
            name='memory_used',
            field=models.BigIntegerField(default=0, verbose_name='Memory Used'),
        ),
        migrations.AlterField(
            model_name='harvester',
            name='nc_process_cnt',
            field=models.IntegerField(default=0, verbose_name='NC Process CNT'),
        ),
        migrations.AlterField(
            model_name='harvester',
            name='server_number',
            field=models.CharField(default='001', max_length=50, verbose_name='Server Id'),
        ),
        migrations.AlterField(
            model_name='harvester',
            name='space_free_plots',
            field=models.IntegerField(default=0, verbose_name='Free Plots'),
        ),
        migrations.AlterField(
            model_name='harvester',
            name='total_current_plots',
            field=models.IntegerField(default=0, verbose_name='Plots'),
        ),
        migrations.AlterField(
            model_name='harvester',
            name='uptime',
            field=models.IntegerField(blank=True, default=0, verbose_name='Uptime'),
        ),
        migrations.AlterField(
            model_name='harvesterservice',
            name='harvester',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='server.harvester', verbose_name='Harvester'),
        ),
        migrations.AlterField(
            model_name='harvesterservice',
            name='index',
            field=models.IntegerField(default=0, verbose_name='Index'),
        ),
        migrations.AlterField(
            model_name='harvesterservice',
            name='local_power',
            field=models.FloatField(default=0, verbose_name='Local Power'),
        ),
        migrations.AlterField(
            model_name='harvesterservice',
            name='remote_power',
            field=models.FloatField(default=0, verbose_name='Remote Power'),
        ),
        migrations.AlterField(
            model_name='harvesterservice',
            name='remote_unit',
            field=models.CharField(blank=True, default='TB', max_length=20, verbose_name='Remote Unit'),
        ),
        migrations.AlterField(
            model_name='harvesterservice',
            name='service',
            field=models.CharField(default='001', max_length=50, verbose_name='Service Name'),
        ),
        migrations.AlterField(
            model_name='harvesterservice',
            name='status',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='harvesterservicerestart',
            name='harvester',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='server.harvester', verbose_name='Harvester'),
        ),
        migrations.AlterField(
            model_name='harvesterservicerestart',
            name='reason',
            field=models.CharField(default='001', max_length=50, verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='harvesterservicerestart',
            name='service',
            field=models.CharField(default='001', max_length=50, verbose_name='Service Name'),
        ),
        migrations.AlterField(
            model_name='harvesterservicerestart',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Restart Time'),
        ),
        migrations.AlterField(
            model_name='plotconfig',
            name='cache_type',
            field=models.CharField(choices=[('3.2*1', '3.2*1'), ('3.2*2', '3.2*2'), ('4.0*1', '4.0*1'), ('4.0*2', '4.0*2'), ('6.4*1', '6.4*1'), ('6.4*2', '6.4*2'), ('4.0*4', '4.0*4'), ('2.0(m2)m*4', '2.0(m2)m*4')], default='3.2*1', max_length=20, verbose_name='Cache Type'),
        ),
        migrations.AlterField(
            model_name='plotconfig',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='plotconfig',
            name='e',
            field=models.BooleanField(default=True, verbose_name='Bitfield'),
        ),
        migrations.AlterField(
            model_name='plotconfig',
            name='global_max_jobs',
            field=models.IntegerField(default=12, verbose_name='Max Jobs'),
        ),
        migrations.AlterField(
            model_name='plotconfig',
            name='global_stagger_m',
            field=models.IntegerField(default=24, verbose_name='Stagger'),
        ),
        migrations.AlterField(
            model_name='plotconfig',
            name='job_buffer',
            field=models.IntegerField(default=4000, verbose_name='Job Buffer'),
        ),
        migrations.AlterField(
            model_name='plotconfig',
            name='k',
            field=models.CharField(default='32', max_length=10, verbose_name='K Size'),
        ),
        migrations.AlterField(
            model_name='plotconfig',
            name='n_buckets',
            field=models.IntegerField(default=128, verbose_name='Buckets'),
        ),
        migrations.AlterField(
            model_name='plotconfig',
            name='n_threads',
            field=models.IntegerField(default=3, verbose_name='Threads'),
        ),
        migrations.AlterField(
            model_name='plotconfig',
            name='name',
            field=models.CharField(default='Config Name', max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='plotconfig',
            name='tmpdir_max_jobs',
            field=models.IntegerField(default=12, verbose_name='Max Jobs(Tmp)'),
        ),
        migrations.AlterField(
            model_name='plotconfig',
            name='tmpdir_stagger_phase_limit',
            field=models.IntegerField(default=5, verbose_name='Phase Limit'),
        ),
        migrations.AlterField(
            model_name='plotconfig',
            name='tmpdir_stagger_phase_major',
            field=models.IntegerField(default=2, verbose_name='Phase Major'),
        ),
        migrations.AlterField(
            model_name='plotconfig',
            name='tmpdir_stagger_phase_minor',
            field=models.IntegerField(default=1, verbose_name='Phase Minor'),
        ),
        migrations.AlterField(
            model_name='plotkey',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='plotkey',
            name='farmer_pk',
            field=models.CharField(default='', max_length=250, verbose_name='Farmer Key'),
        ),
        migrations.AlterField(
            model_name='plotkey',
            name='name',
            field=models.CharField(default='Config Name', max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='plotkey',
            name='pool_key',
            field=models.CharField(default='', max_length=250, verbose_name='Pool Key'),
        ),
        migrations.AlterField(
            model_name='plotter',
            name='boot_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Boot Time'),
        ),
        migrations.AlterField(
            model_name='plotter',
            name='cpu_cnt',
            field=models.IntegerField(default=0, verbose_name='CPU Count'),
        ),
        migrations.AlterField(
            model_name='plotter',
            name='cpu_model',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='CPU'),
        ),
        migrations.AlterField(
            model_name='plotter',
            name='cpu_used_percent',
            field=models.FloatField(default=0, verbose_name='CPU Used Percent'),
        ),
        migrations.AlterField(
            model_name='plotter',
            name='data_interface',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Data Network Card'),
        ),
        migrations.AlterField(
            model_name='plotter',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='plotter',
            name='exclude_plot_dst_path',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Exclude Dst Paths'),
        ),
        migrations.AlterField(
            model_name='plotter',
            name='harvester',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plotters', to='server.harvester', verbose_name='Harvester'),
        ),
        migrations.AlterField(
            model_name='plotter',
            name='internal_ip',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Internal IP'),
        ),
        migrations.AlterField(
            model_name='plotter',
            name='is_cache_raid',
            field=models.BooleanField(default=False, verbose_name='Cache Raid'),
        ),
        migrations.AlterField(
            model_name='plotter',
            name='is_monero_run',
            field=models.BooleanField(default=False, verbose_name='Monero'),
        ),
        migrations.AlterField(
            model_name='plotter',
            name='is_plotting_run',
            field=models.BooleanField(default=False, verbose_name='Plotting'),
        ),
        migrations.AlterField(
            model_name='plotter',
            name='is_sending_run',
            field=models.BooleanField(default=False, verbose_name='Sending'),
        ),
        migrations.AlterField(
            model_name='plotter',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='HeartBeat'),
        ),
        migrations.AlterField(
            model_name='plotter',
            name='memory_total',
            field=models.BigIntegerField(default=0, verbose_name='Memory Total'),
        ),
        migrations.AlterField(
            model_name='plotter',
            name='memory_used',
            field=models.BigIntegerField(default=0, verbose_name='Memory Used'),
        ),
        migrations.AlterField(
            model_name='plotter',
            name='nvme_cnt',
            field=models.IntegerField(default=1, verbose_name='NVME Count'),
        ),
        migrations.AlterField(
            model_name='plotter',
            name='nvme_size',
            field=models.FloatField(default=0, verbose_name='NVME Size'),
        ),
        migrations.AlterField(
            model_name='plotter',
            name='plot_cnt',
            field=models.IntegerField(default=0, verbose_name='Plot Count'),
        ),
        migrations.AlterField(
            model_name='plotter',
            name='plot_config',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plotters', to='server.plotconfig', verbose_name='PlotConfig'),
        ),
        migrations.AlterField(
            model_name='plotter',
            name='plot_config_applied',
            field=models.BooleanField(default=False, verbose_name='Plot Config Applied'),
        ),
        migrations.AlterField(
            model_name='plotter',
            name='plot_file_path',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Plot File Path'),
        ),
        migrations.AlterField(
            model_name='plotter',
            name='plot_file_path_expand',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Plot File Path(Expand)'),
        ),
        migrations.AlterField(
            model_name='plotter',
            name='server_number',
            field=models.CharField(default='001', max_length=50, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='plotter',
            name='st_avg_copy_time',
            field=models.FloatField(default=0, verbose_name='Copy Time'),
        ),
        migrations.AlterField(
            model_name='plotter',
            name='st_avg_plot_time',
            field=models.FloatField(default=0, verbose_name='Plot Time'),
        ),
        migrations.AlterField(
            model_name='plotter',
            name='st_plot_output',
            field=models.IntegerField(default=0, verbose_name='Output'),
        ),
        migrations.AlterField(
            model_name='plotter',
            name='st_plot_process_cnt',
            field=models.IntegerField(default=0, verbose_name='Process'),
        ),
        migrations.AlterField(
            model_name='plotter',
            name='st_update_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='UpdateTime'),
        ),
        migrations.AlterField(
            model_name='plotter',
            name='uptime',
            field=models.IntegerField(blank=True, default=0, verbose_name='Uptime'),
        ),
        migrations.AlterField(
            model_name='plottransfer',
            name='harvester_ip',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Harvester IP'),
        ),
        migrations.AlterField(
            model_name='plottransfer',
            name='harvester_path',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Path'),
        ),
        migrations.AlterField(
            model_name='plottransfer',
            name='harvester_server',
            field=models.CharField(default='harvester-001', max_length=50, verbose_name='Harvester Server'),
        ),
        migrations.AlterField(
            model_name='plottransfer',
            name='nc_pid',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='NC pid'),
        ),
        migrations.AlterField(
            model_name='plottransfer',
            name='nc_port',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='NC port'),
        ),
        migrations.AlterField(
            model_name='plottransfer',
            name='plot_check',
            field=models.BooleanField(default=False, verbose_name='Plot Check'),
        ),
        migrations.AlterField(
            model_name='plottransfer',
            name='plot_check_fail_reason',
            field=models.BooleanField(default=False, verbose_name='Plot Check Fail Reason'),
        ),
        migrations.AlterField(
            model_name='plottransfer',
            name='plot_file_name',
            field=models.CharField(default='default name', max_length=254, verbose_name='Plot File'),
        ),
        migrations.AlterField(
            model_name='plottransfer',
            name='plotter_ip',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Plotter IP'),
        ),
        migrations.AlterField(
            model_name='plottransfer',
            name='plotter_path',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Path'),
        ),
        migrations.AlterField(
            model_name='plottransfer',
            name='plotter_server',
            field=models.CharField(default='plotter-001', max_length=50, verbose_name='Plotter Server'),
        ),
        migrations.AlterField(
            model_name='plottransfer',
            name='txn_start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='plottransfer',
            name='txn_stop_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Start Time'),
        ),
    ]
